web:
  restart: always
  build: ./
  container_name: web2
  expose:
    - "8000"
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

nginx:
  restart: always
  build: ./nginx/
  container_name: nginx2
  ports:
   - "8080:80" 
  links:
    - web:web
